document.documentElement.classList.add('js');const header=document.querySelector('[data-header]');const menuButton=document.querySelector('.menu-button');const nav=document.querySelector('#site-nav');
menuButton?.addEventListener('click',()=>{const open=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!open));nav.classList.toggle('open',!open)});
nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuButton?.setAttribute('aria-expanded','false')}));
addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>24),{passive:true});
document.querySelectorAll('.service-toggle').forEach(button=>button.addEventListener('click',()=>{const service=button.closest('.service');const open=service.classList.toggle('open');button.setAttribute('aria-expanded',String(open))}));
const observer='IntersectionObserver'in window?new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12}):null;
document.querySelectorAll('.reveal').forEach(element=>observer?observer.observe(element):element.classList.add('visible'));
document.querySelector('[data-year]').textContent=new Date().getFullYear();
const policies={privacy:`<h2>Privacy notice</h2><p class="policy-notice"><strong>Launch draft:</strong> the owner must add the approved legal identity, contact details, jurisdiction, and effective date before publication.</p><h3>Information you choose to share</h3><p>This static website does not provide user accounts or an on-site payment form. If you open WhatsApp or another external service, information you submit is handled by that service and by the studio for responding to your inquiry.</p><h3>Technical data</h3><p>The hosting provider may process standard request data needed to deliver and protect the website. No optional analytics or advertising trackers are included in this version.</p><h3>Client records</h3><p>After a project is agreed, proposals, contracts, invoices, and payment records may be processed through Bonsai and the selected payment provider, subject to their terms.</p>`,terms:`<h2>Terms of use</h2><p class="policy-notice"><strong>Launch draft:</strong> these terms require owner and legal review before publication. No legal entity, address, or jurisdiction has been invented.</p><h3>Website information</h3><p>Website content is general information and does not create a client relationship, project commitment, or guarantee of results.</p><h3>Project agreements</h3><p>Services begin only after both sides agree in writing on scope, deliverables, timing, responsibilities, and price. The final proposal, contract, or invoice governs that engagement.</p><h3>Third-party services</h3><p>WhatsApp, Bonsai, Stripe, Wise, Payoneer, and banking providers operate under their own terms and availability. Mentioning a method does not guarantee availability in every country or account.</p>`,refund:`<h2>Refund policy</h2><p class="policy-notice"><strong>Launch draft:</strong> the owner must approve this policy and align it with the applicable jurisdiction and final contract terms before publication.</p><h3>Before work starts</h3><p>Any cancellation or refund right will be stated in the agreed proposal, contract, or invoice.</p><h3>Work already performed</h3><p>Fees for completed milestones, delivered work, reserved time, or non-recoverable costs may not be refundable where permitted and agreed.</p><h3>How to raise a concern</h3><p>Contact the studio through the same WhatsApp conversation used for the engagement. Each request is reviewed against the written project agreement and payment record.</p>`};
const dialog=document.querySelector('[data-policy-dialog]');const content=document.querySelector('[data-policy-content]');document.querySelectorAll('[data-policy]').forEach(button=>button.addEventListener('click',()=>{content.innerHTML=policies[button.dataset.policy];dialog.showModal()}));document.querySelector('.dialog-close')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});

